const FRASES = [
  // 1–10
  "Dia 1 do nosso livrinho. Que ele se encha de nós dois, uma página de cada vez.",
  "Bom dia pra quem transforma qualquer dia comum no meu dia favorito.",
  "Você é a parte mais bonita da minha rotina.",
  "Eu gosto de quem eu sou quando estou do seu lado.",
  "Se eu pudesse escolher um lugar no mundo, seria do seu lado.",
  "Hoje eu só queria te lembrar: eu escolho você. De novo e sempre.",
  "Seu sorriso ainda me desmonta todas as vezes.",
  "Tem dias que eu nem acredito na sorte de ter te encontrado.",
  "Você é o meu lugar favorito pra descansar.",
  "Que hoje o mundo seja gentil com você, do mesmo jeito que você é com ele.",
  // 11–20
  "O nosso amor tem cheiro de casa.",
  "Eu ainda fico bobo quando você fala o meu nome.",
  "Você não faz ideia do bem que me faz.",
  "Cada plano que a gente escreve aqui já é meio caminho andado.",
  "Com você, até fila de banco vira passeio.",
  "Você é o sim mais bonito que a vida já me deu.",
  "Eu te amo nos dias bons, e mais ainda nos difíceis.",
  "Obrigado por ser o meu abraço preferido.",
  "{nome}, você é poesia sem precisar de rima.",
  "Hoje é um ótimo dia pra escrever um desejo novo aqui no livrinho.",
  // 21–30
  "Quero conhecer o mundo inteiro, mas só se for com você.",
  "Meu coração tem o seu endereço.",
  "Você deixa tudo mais leve, até eu.",
  "Te amar é a coisa mais fácil que eu já fiz.",
  "Se hoje estiver pesado, lembra: eu estou do seu lado. Sempre.",
  "Tem um pedacinho de mim que só aparece quando você está por perto.",
  "O nosso futuro tem cara de domingo de manhã.",
  "Você é o meu motivo favorito pra sorrir do nada.",
  "Eu faria todos os caminhos de novo só pra te encontrar outra vez.",
  "Um mês de frases, e a vontade de você só aumenta.",
  // 31–40
  "Você brilha até nos dias em que se acha apagadinha.",
  "Eu queria te dar o mundo. Por enquanto, te dou o meu coração inteiro.",
  "A gente combina até no silêncio.",
  "Tudo que é bom fica melhor quando eu divido com você.",
  "{nome}, você é o meu melhor acaso.",
  "Que tal colar uma foto nossa hoje?",
  "O amor mais bonito é o que vira amizade, parceria e casa.",
  "Você é a minha paz em forma de gente.",
  "Eu gosto da gente. Muito.",
  "Sabe aquele frio na barriga? Ainda sinto por você.",
  // 41–50
  "Não existe distância que diminua o que eu sinto.",
  "Você me faz querer ser melhor, sem nem perceber.",
  "Com você eu aprendi que o amor mora nos detalhes.",
  "Hoje eu te amo um pouquinho mais do que ontem. Amanhã, mais ainda.",
  "Os nossos sonhos ficam lindos escritos lado a lado.",
  "Você é a resposta de uma pergunta que eu nem sabia que tinha.",
  "Obrigado por me escolher todos os dias.",
  "O seu abraço deveria ser patrimônio da humanidade.",
  "Eu amo o jeito que você ri das minhas piadas ruins.",
  "Cinquenta frases depois, ainda falta palavra pra dizer o quanto te amo.",
  // 51–60
  "Seja gentil com você hoje. Você merece.",
  "Onde você estiver, é lá que eu quero estar.",
  "Você é a minha aventura favorita.",
  "{nome}, se o amor tivesse um rosto, teria o seu sorriso.",
  "Um dia a gente vai rir lembrando de hoje. Juntinhos.",
  "Eu guardo cada momento nosso como quem guarda um tesouro.",
  "Você chegou e bagunçou tudo do jeito mais bonito.",
  "O meu som preferido é a sua risada.",
  "Tem gente que procura o paraíso. Eu encontrei no seu abraço.",
  "Que a nossa história seja longa, leve e cheia de viagens.",
  // 61–70
  "Você é linda de todos os jeitos, principalmente do seu.",
  "Posso ser sincero? Você é a melhor parte do meu dia.",
  "Com você eu não preciso fingir nada.",
  "A gente ainda vai viver tanta coisa boa. Anota aí.",
  "Você é o meu pensamento de bom dia e de boa noite.",
  "Eu te amo em todos os idiomas que eu ainda não sei falar.",
  "Mais um dia pra gente se escolher. Eu já escolhi.",
  "O nosso amor não precisa ser perfeito. Só precisa ser nosso.",
  "Quando eu penso em futuro, eu penso em você.",
  "{nome}, obrigado por existir exatamente do jeito que você é.",
  // 71–80
  "Você é o meu lugar seguro.",
  "Até o café fica mais gostoso quando é com você.",
  "Eu quero colecionar pores do sol ao seu lado.",
  "A vida ficou mais colorida depois que você chegou.",
  "Eu tenho orgulho de você, sabia? Muito.",
  "Me conta um sonho seu? Aqui no livrinho tem espaço pra todos.",
  "O seu jeito de cuidar de mim é a coisa mais linda que eu conheço.",
  "Você me faz acreditar em felizes para sempre.",
  "Não existe dia ruim que o seu abraço não melhore.",
  "Eu gosto até das nossas manias.",
  // 81–90
  "Você é a minha pessoa. Simples assim.",
  "O melhor lugar do mundo é qualquer um com você.",
  "Um passo de cada vez, mas sempre de mãos dadas.",
  "Você é a estrela mais bonita do meu céu.",
  "Você é tudo o que eu sempre quis, e um pouco mais.",
  "Os nossos planos não têm pressa. Mas têm certeza.",
  "Hoje eu quero te lembrar do quanto você é incrível.",
  "Você é casa, colo e aventura ao mesmo tempo.",
  "{nome}, o meu coração bate diferente quando você chega.",
  "Noventa dias de frases, e cada uma foi pensada em você.",
  // 91–100
  "Se a vida é uma viagem, você é o meu destino favorito.",
  "Com você, o simples vira especial.",
  "Obrigado pela paciência, pelo carinho e por cada risada.",
  "Eu ainda sonho acordado com a gente.",
  "Você é o meu “vai ficar tudo bem”.",
  "A melhor decisão que eu já tomei foi amar você.",
  "Eu me perco no seu olhar e não quero achar a saída.",
  "Quero envelhecer contando as nossas histórias.",
  "Você é o capítulo mais bonito da minha vida.",
  "Cem dias de frases! E eu ainda tenho um mundo de coisas pra te dizer.",
  // 101–110
  "O que eu sinto por você não cabe neste livrinho. Mas eu tento.",
  "Você faz o meu coração sorrir.",
  "Hoje é dia de marcar algum desejo como realizado?",
  "Com você eu aprendi que amar é coisa que se faz todo dia.",
  "Você é a minha calmaria no meio do caos.",
  "Te ver feliz é o meu passatempo favorito.",
  "Você é tudo aquilo que eu pedi em silêncio.",
  "Conversar com você é o meu jeito favorito de gastar o tempo.",
  "{nome}, o universo caprichou quando fez você.",
  "A saudade de você chega rápido demais.",
  // 111–120
  "Te amar é o que eu faço de melhor.",
  "Você me ensina coisas que nenhum livro ensina.",
  "Ainda vamos dançar na cozinha de casa, de pijama.",
  "O seu sorriso é o meu remédio pra qualquer dia cinza.",
  "Você é a minha certeza no meio de tanta dúvida.",
  "Eu amo o seu jeitinho de falar comigo.",
  "Juntos a gente vai longe. Literalmente: olha a nossa lista de viagens.",
  "Você é a primeira pessoa pra quem eu quero contar as coisas boas.",
  "Cada dia do seu lado é um presente.",
  "Tudo que você toca fica um pouco mais bonito.",
  // 121–130
  "Você é o meu melhor “e se…” que deu certo.",
  "Obrigado por acreditar em mim até quando eu duvido.",
  "O seu abraço tem o tamanho exato do meu coração.",
  "Hoje eu te amo como se fosse o primeiro dia.",
  "A gente é time. Sempre.",
  "{nome}, você merece todas as coisas bonitas do mundo.",
  "Eu quero ser o motivo de pelo menos um sorriso seu hoje.",
  "Você é a minha pessoa favorita pra não fazer nada.",
  "O nosso amor é feito de pequenas coisas enormes.",
  "Com você o tempo passa rápido demais.",
  // 131–140
  "Você é a luz que eu procuro no fim do dia.",
  "Tem tanto sonho nosso esperando pra virar lembrança.",
  "Você me conhece como ninguém.",
  "Deitar no seu colo resolve metade dos meus problemas.",
  "O seu nome é o meu assunto preferido.",
  "Não importa o destino. Importa quem está do lado.",
  "Você é linda por fora, mas por dentro é ainda mais.",
  "Gosto de pensar que a gente foi feito pra se encontrar.",
  "Hoje, respira fundo e lembra: você é muito amada.",
  "Um dia comum com você vale mais que qualquer feriado sem você.",
  // 141–150
  "Um dia a página de viagens vai estar cheia de lugares onde a gente já foi.",
  "Você é o meu presente e o meu futuro.",
  "{nome}, eu te escolheria em qualquer universo.",
  "O seu cafuné deveria ser vendido em farmácia.",
  "A gente não precisa de muito. Só da gente.",
  "Você é a minha saudade favorita.",
  "Quero te ver sorrindo assim pra sempre.",
  "O nosso amor é bonito porque é verdadeiro.",
  "Você é tudo o que o meu coração precisava.",
  "Cento e cinquenta dias! Já te disse hoje que você é incrível?",
  // 151–160
  "Eu adoro quando você fica toda animada falando de algo que ama.",
  "Os seus olhos contam histórias que eu quero ler pra sempre.",
  "O mundo é grande, mas o meu lugar é com você.",
  "Eu amo os nossos planos de madrugada.",
  "Você me faz rir justamente quando eu mais preciso.",
  "Te amo daqui até a lua, ida e volta. Duas vezes.",
  "O nosso amor tem gosto de pipoca, filme e cobertor.",
  "Você é sol até em dia de chuva.",
  "Obrigado pelos abraços apertados e pelos beijos demorados.",
  "{nome}, você é a minha melhor escolha.",
  // 161–170
  "Hoje é um bom dia pra planejar a próxima viagem.",
  "Se foi destino ou acaso, eu agradeço os dois.",
  "Se precisar, eu seguro a sua mão. Se não precisar, eu seguro também.",
  "A nossa história ainda está só começando.",
  "O seu jeito de ser é a coisa mais bonita que eu já vi.",
  "Você é o meu sonho que deu certo.",
  "Eu te amo com tudo o que eu sou.",
  "Qualquer cidade vira casa se você estiver nela.",
  "Eu conto as horas pra te ver. Sempre.",
  "Tem coisas que só fazem sentido com você.",
  // 171–180
  "A nossa história é a minha preferida.",
  "Você é linda até de cara amassada. Principalmente de cara amassada.",
  "Eu quero construir uma vida inteira com você.",
  "{nome}, você faz o meu mundo girar mais bonito.",
  "Hoje eu te desejo um dia leve e cheio de coisas boas.",
  "Você é o meu refúgio.",
  "A gente se completa até nos defeitos.",
  "Eu amo as nossas conversas sem fim.",
  "Você é o melhor presente que eu já ganhei.",
  "O seu amor me deixa mais forte.",
  // 181–190
  "Quero te dar bom dia pelo resto da vida.",
  "Obrigado por tornar os meus dias tão mais bonitos.",
  "Metade do caminho: 182 frases pra trás, 182 pela frente. E uma surpresa lá no fim.",
  "Eu gosto de você de um jeito que não cabe em frase nenhuma.",
  "Cada foto nossa aqui guarda um pedacinho de felicidade.",
  "Você é a razão do meu sorriso bobo no meio da rua.",
  "Eu quero ser a sua calma nos dias agitados.",
  "Nada é tão bom quanto te encontrar depois de um dia longo.",
  "{nome}, você é a minha pessoa preferida no mundo inteiro.",
  "O amor que você me dá me ensina a amar melhor.",
  // 191–200
  "Hoje, reserva um tempinho só pra você. Eu vou estar torcendo daqui.",
  "Um dia a gente vai olhar pra este livrinho e sorrir de tudo o que viveu.",
  "O seu bom dia muda o meu dia inteiro.",
  "Eu gosto de te ver dormindo. Parece que o mundo fica em paz.",
  "Somos dois, mas às vezes parece que é um só coração.",
  "Quero te levar pra ver o mar mais bonito que existir.",
  "Você é a minha âncora e as minhas asas ao mesmo tempo.",
  "Obrigado por segurar a minha mão quando o chão treme.",
  "A gente ainda tem tanta coisa pra riscar da lista. Que delícia.",
  "Duzentos dias de frases, e o meu amor só aumenta.",
  // 201–210
  "Você é o motivo de eu acreditar em coisas bonitas.",
  "O seu cheiro é a minha lembrança preferida.",
  "Se for pra sonhar, que seja com você.",
  "Com você, eu aprendi que o amor pode ser tranquilo.",
  "{nome}, a vida ficou mais doce desde que você chegou.",
  "Eu amo o jeito que você me olha quando acha que eu não estou vendo.",
  "Hoje é um bom dia pra colar mais uma foto nossa.",
  "O nosso amor é o meu projeto de vida favorito.",
  "Você é mais bonita que qualquer paisagem que a gente ainda vai ver.",
  "A gente vai longe. Juntos é mais bonito.",
  // 211–220
  "Com você, eu tenho vontade de fazer planos.",
  "Um beijo seu vale mais que mil palavras.",
  "Eu te amo, e isso é a coisa mais certa que eu sei.",
  "Você deixa a vida com gosto de férias.",
  "Mesmo nos dias corridos, você é o meu pensamento favorito.",
  "Eu queria que você se visse com os meus olhos.",
  "O seu riso é contagiante, e eu sou sempre o primeiro a pegar.",
  "Cada dia contigo é uma página nova que eu adoro escrever.",
  "Obrigado por deixar eu fazer parte da sua vida.",
  "{nome}, tudo fica no lugar quando você está por perto.",
  // 221–230
  "Que nunca falte carinho, risada e viagem pra gente.",
  "Eu amo quem você é e quem você está se tornando.",
  "Você é o meu desejo realizado mais bonito.",
  "Tem gente que ilumina o ambiente. Você ilumina a minha vida.",
  "A nossa lista de desejos é a lista de compras da felicidade.",
  "Pode contar comigo pra tudo. Pra tudo mesmo.",
  "Você fica linda de qualquer jeito, mas feliz fica mais ainda.",
  "Quero passar todos os domingos preguiçosos com você.",
  "O meu coração é seu. Já faz tempo.",
  "Obrigado por cada “se cuida” e cada “chegou bem?”.",
  // 231–240
  "Você é gentil de um jeito raro. Nunca deixe o mundo mudar isso.",
  "Eu já te disse hoje que te amo? Então: te amo.",
  "Juntos, a gente transforma sonho em plano.",
  "{nome}, você merece um amor do tamanho do mundo. Eu estou tentando.",
  "Você é o abraço que eu quero no fim de todo dia.",
  "O melhor da vida é dividir a vida com você.",
  "Mal posso esperar pelas próximas páginas da nossa história.",
  "Você me faz bem até de longe.",
  "Te amo nos detalhes, nas manias e nos silêncios.",
  "Hoje, sorria. Alguém aqui é completamente apaixonado por você.",
  // 241–250
  "Se eu tivesse um pedido, seria mais tempo com você.",
  "Você é a minha melhor companhia.",
  "A cada dia eu descubro um motivo novo pra te amar.",
  "Você é meu amor, minha amiga e minha parceira de aventura.",
  "Tem um sorriso bobo aqui só de pensar em você.",
  "{nome}, obrigado por cada momento, até os mais simples.",
  "Quero conhecer lugares novos e voltar sempre pra você.",
  "O amor da gente é leve, e é por isso que ele voa alto.",
  "Nunca duvide do quanto você é importante pra mim.",
  "Duzentos e cinquenta dias! Faltam só 115 pra surpresa.",
  // 251–260
  "Você é a minha inspiração diária.",
  "Quero ver o nascer do sol com você em algum lugar bem longe.",
  "Você é a pessoa que eu mais admiro.",
  "Obrigado por me amar do seu jeitinho.",
  "Eu te amo mais do que café na segunda-feira.",
  "Do seu lado, tudo parece possível.",
  "Se a gente fosse um filme, eu assistiria mil vezes.",
  "{nome}, só de pensar em você o dia já melhora.",
  "Que a gente nunca perca o costume de se admirar.",
  "Você é o meu “até logo” mais difícil e o meu “oi” mais feliz.",
  // 261–270
  "Eu quero realizar cada desejo desta lista ao seu lado.",
  "Você me faz acreditar no amor todos os dias.",
  "Eu não canso de olhar o seu sorriso.",
  "Você tem um coração enorme. Eu tenho sorte de morar nele.",
  "Tudo o que eu quero está do seu lado.",
  "Tem dias que eu só quero um abraço seu. Hoje é um deles.",
  "O nosso amor é o meu maior orgulho.",
  "Você é a melhor coisa que me aconteceu.",
  "{nome}, eu te amo mais a cada página.",
  "A gente se entende só no olhar.",
  // 271–280
  "Você merece ser amada todos os dias. E vai.",
  "Cada viagem com você vira a melhor viagem.",
  "Você é a minha melhor amiga, com direito a beijo.",
  "A felicidade tem o seu jeito.",
  "Eu vou estar aqui, hoje e em todos os capítulos.",
  "Se isso for um sonho, por favor, não me acorda.",
  "Quero ser o seu abrigo em qualquer tempestade.",
  "Você me faz rir, me faz pensar e me faz feliz.",
  "Contigo, a vida é mais divertida.",
  "{nome}, você é o meu melhor pensamento.",
  // 281–290
  "O amor que a gente tem, a gente constrói junto. E isso é lindo.",
  "Obrigado por não desistir de nós nos dias difíceis.",
  "Você é linda quando acorda, quando ri e até quando fica brava.",
  "Um desejo realizado por vez, e a vida vai ficando do jeito que a gente sonhou.",
  "Você é o meu coração batendo fora do peito.",
  "Eu amo o jeito que você segura a minha mão.",
  "Você é a surpresa boa que a vida me fez.",
  "Mais um dia, mais uma chance de te fazer feliz.",
  "Com você, o futuro dá vontade de chegar logo.",
  "Hoje eu te amo. Amanhã também. E depois, e depois…",
  // 291–300
  "A sua felicidade é uma das minhas prioridades.",
  "Você deixa o mundo mais bonito só por estar nele.",
  "{nome}, eu gosto de você de um jeito que é só seu.",
  "Quero dividir contigo todos os pratos de comida… quase todos.",
  "O melhor presente é o seu tempo comigo.",
  "Você é o meu “pra sempre” favorito.",
  "Eu sou muito grato por você.",
  "Te amo de um jeito que nem eu sei explicar.",
  "Quem diria que um dia eu ia amar tanto assim.",
  "Trezentos dias de frases! A surpresa já está chegando…",
  // 301–310
  "Eu releria a nossa história mil vezes sem pular nenhuma página.",
  "Cada momento com você vira lembrança boa.",
  "Obrigado por cuidar do meu coração com tanto carinho.",
  "Eu te amo em câmera lenta e em avanço rápido.",
  "{nome}, eu quero te ver realizando todos os seus sonhos.",
  "Com você, até o caminho mais longo parece curto.",
  "Eu te escolho hoje, amanhã e em todos os dias do calendário.",
  "Você é a minha dose diária de felicidade.",
  "O seu jeito doce desarma qualquer dia difícil.",
  "Quero uma vida inteira de viagens, e de voltas pra casa com você.",
  // 311–320
  "Você é o meu sossego e a minha festa.",
  "Você fica ainda mais bonita quando está sendo você mesma.",
  "Eu ainda leio as suas mensagens com um sorriso bobo.",
  "Amo cada pedacinho da nossa história.",
  "{nome}, a sua existência já deixa o meu dia melhor.",
  "Tem amor que acalma. O seu me acalma e me acende.",
  "Você é o meu melhor plano.",
  "Com você, eu quero todas as primeiras vezes e todas as de novo.",
  "Eu penso em você mais vezes do que admito.",
  "Hoje é um bom dia pra reler as páginas deste livrinho.",
  // 321–330
  "Você é a pessoa que eu quero em todas as fotos.",
  "Cada “eu te amo” seu ainda me pega de surpresa.",
  "Eu adoro o nosso jeito bobo de ser.",
  "Você é a razão do meu coração bater mais rápido.",
  "{nome}, obrigado por fazer a vida ficar tão bonita.",
  "Juntos, até o impossível parece logo ali.",
  "Você me conhece e mesmo assim me ama. Isso é mágico.",
  "Eu quero ser a sua pessoa por muito, muito tempo.",
  "O seu carinho é a coisa mais bonita que eu já recebi.",
  "Obrigado por cada dia deste ano. Cada um deles.",
  // 331–340
  "Você é o meu melhor começo, o meu meio e tudo o que vier depois.",
  "A vida com você é a vida que eu quero.",
  "Tem tanta coisa linda que eu ainda quero viver contigo.",
  "{nome}, eu te amo com calma, com pressa e com tudo.",
  "Faltam trinta dias pra surpresa. Eu já estou nervoso.",
  "Você é a minha memória favorita e o meu plano favorito.",
  "Quero te fazer rir até doer a barriga.",
  "Com você, eu aprendi a gostar do devagarinho.",
  "Você é o meu melhor motivo pra acordar cedo. Ou dormir tarde.",
  "Eu amo como você transforma qualquer lugar em nosso.",
  // 341–350
  "O nosso livrinho está ficando lindo, igual a gente.",
  "Você é a minha pessoa preferida pra dividir sobremesa.",
  "{nome}, você é a melhor notícia de todos os meus dias.",
  "Que cada dia seja uma desculpa pra gente se amar mais.",
  "Eu me apaixono por você em doses diárias.",
  "Você é o meu pedido em todo ano-novo.",
  "Se eu pudesse, parava o tempo nos nossos abraços.",
  "Este livrinho guarda o ano mais bonito da minha vida.",
  "Você me faz querer escrever mais mil páginas.",
  "Quinze dias pra surpresa. Paciência, meu amor.",
  // 351–360
  "Você é tudo o que eu quero pra hoje e pra sempre.",
  "Obrigado por transformar planos em lembranças comigo.",
  "Eu te amo nos dias de sol e nos de chuva também.",
  "{nome}, o meu coração sabe o seu nome de cor.",
  "Dez dias pra surpresa. O coração já está acelerado.",
  "Tudo o que eu vivi me trouxe até você. Valeu cada passo.",
  "Um ano quase inteiro de você, e eu quero mais.",
  "Uma semana pra surpresa. Já está curiosa?",
  "Seis dias. E em cada um deles eu vou estar te amando.",
  "Cinco dias. Eu contando nos dedos, você contando as páginas.",
  // 361–365
  "{nome}, obrigado por ler cada frase deste livrinho.",
  "Três dias. Eu estou mais ansioso que você, garanto.",
  "Dois dias! Guarda um espaço no coração pra surpresa.",
  "Amanhã é o grande dia. Dorme pensando em mim?",
  "Dia 365. Um ano inteirinho de frases pra você. Agora vai até a última página: tem uma surpresa te esperando."
];
